Repository thoth-station/invectio, pull requests merged in 2019-07, with the labels that each got.

#15 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#16 Do not use setup.cfg, use setup.py
  setup.cfg
  setup.py
Labels: approved, size/M

#18 Release of version 0.0.4
  CHANGELOG.md
  invectio/__init__.py
Labels: bot, size/XS

#19 Add version information to invectio reports
  invectio/lib.py
  tests/test_lib.py
Labels: approved, size/M, size/XS

#21 Release of version 0.0.5
  CHANGELOG.md
  invectio/__init__.py
Labels: bot, size/XS
