Repository thoth-station/invectio, pull requests merged in 2019-08, with the labels that each got.

#22 Detection of Python's standard libraries
  invectio/__init__.py
  invectio/cli.py
  invectio/lib.py
  tests/data/app_7.py
  tests/test_lib.py
Labels: approved, size/M

#24 Release of version 0.0.6
  CHANGELOG.md
  invectio/__init__.py
Labels: bot, size/XS

#25 Automatic update of dependency daiquiri from 1.5.0 to 1.6.0
  Pipfile.lock
Labels: bot

#27 Introduce without-builtin-imports option
  invectio/cli.py
  invectio/lib.py
  tests/data/app_8.py
  tests/test_lib.py
Labels: approved, size/M

#29 Release of version 0.0.7
  CHANGELOG.md
  invectio/__init__.py
Labels: bot, size/XS

#30 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#31 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#33 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
