Repository thoth-station/invectio, pull requests merged in 2020-01, with the labels that each got.

#54 Happy new year!
  invectio/__init__.py
  invectio/cli.py
  invectio/lib.py
  tests/test_lib.py
Labels: approved, size/XS

#55 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/L

#56 Automatic update of dependency daiquiri from 1.6.1 to 2.0.0
  Pipfile.lock
Labels: bot, size/L

#57 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/XS

#58 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#60 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/M
