Repository thoth-station/invectio, pull requests merged in 2020-03, with the labels that each got.

#68 Remove typeshed
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#69 Automatic update of dependency click from 7.0 to 7.1.1
  Pipfile.lock
Labels: bot, size/S

#70 Automatic update of dependency daiquiri from 2.1.0 to 2.1.1
  Pipfile.lock
Labels: bot, size/S

#74 Automatic update of dependency pytest-mypy from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot, size/M

#73 Automatic update of dependency pytest from 5.3.5 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS
