Repository thoth-station/invectio, pull requests merged in 2020-11, with the labels that each got.

#83 Automatic update of dependency pytest from 5.4.3 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#84 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/L

#85 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/L

#87 Automatic update of dependency pytest-mypy from 0.6.2 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/L

#63 Add templates for releases
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: size/M

#81 Add ability to check symbols provided by a lib or Python file
  README.rst
  invectio/__init__.py
  invectio/cli.py
  invectio/lib.py
  setup.py
  tests/data/app_9.py
  tests/test_lib.py
Labels: approved, size/XL

#90 Automatic update of dependency daiquiri from 2.1.1 to 3.0.0
  Pipfile.lock
Labels: approved, bot, size/XS

#92 Release of version 0.1.0
  CHANGELOG.md
  invectio/__init__.py
Labels: approved, bot, size/M

#94 Automatic update of dependency pytest-mypy from 0.7.0 to 0.8.0
  Pipfile.lock
Labels: approved, bot, size/XS

#95 bump python version
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/M
