Repository thoth-station/invectio, pull requests merged in 2020-02, with the labels that each got.

#61 Create .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#62 Add section for Thoth runtime environment to .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#64 Automatic update of dependency pytest-mypy from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot, size/S

#65 Automatic update of dependency daiquiri from 2.0.0 to 2.1.0
  Pipfile.lock
Labels: bot, size/XS

#66 Automatic update of dependency astpretty from 1.7.0 to 2.0.0
  Pipfile.lock
Labels: bot, size/XS
