Repository thoth-station/invectio, pull requests merged in 2022-01, with the labels that each got.

#129 Add a link to the article published on RH developers
  README.rst
Labels: approved, size/XS

#128 fixed typo in url
  README.rst
Labels: approved, size/XS, ok-to-test

#132 Warn about duplicate imports only if source modules differ
  invectio/lib.py
Labels: approved, size/S

#136 Use https instead of git in pre-commit
  .pre-commit-config.yaml
Labels: approved, size/XS

#141 Add template for delivering a missing module
  .github/ISSUE_TEMPLATE/deliver_missing_module.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/S

#142 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS
